### ISSUE TITLE
经典蓝牙扫描设备闪退

### ISSUE THREAD

**Issue by Dachui-Xu** [zhzc0x/BluetoothAssistant#2]
用您提供的apk，我发现选择蓝牙类型是CLASSIC点击扫描设备闪退。
我就把代码在ide中运行，发现于尝试获取一个空数组的长度导致的空指针异常，这部分错误好像与您提供的框架有关，具体错误如下:
```bash
FATAL EXCEPTION: main
                                                                                                    Process: com.example.attitudemonitoring, PID: 16028
                                                                                                    java.lang.NullPointerException: Attempt to get length of null array
                                                                                                    	at com.zhzc0x.bluetooth.client.ClassicClient.startScan(ClassicClient.kt:85)
                                                                                                    	at com.zhzc0x.bluetooth.BluetoothClient.startScan(BluetoothClient.kt:130)
                                                                                                    	at com.example.attitudemonitoring.ui.MainActivity.startScanDevice(MainActivity.kt:410)
                                                                                                    	at com.example.attitudemonitoring.ui.MainActivity.access$startScanDevice(MainActivity.kt:68)
                                                                                                    	at com.example.attitudemonitoring.ui.MainActivity$Content$3.invoke(MainActivity.kt:224)
                                                                                                    	at com.example.attitudemonitoring.ui.MainActivity$Content$3.invoke(MainActivity.kt:224)
                                                                                                    	at com.example.attitudemonitoring.ui.widgets.ScanDeviceDialogKt$ScanDeviceDialog$2$2$1.invokeSuspend(ScanDeviceDialog.kt:102)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8762)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@a45f7df, androidx.compose.runtime.BroadcastFrameClock@6caac2c, StandaloneCoroutine{Cancelling}@ac8e6f5, AndroidUiDispatcher@4672c8a]
```

**Comment by Dachui-Xu** [comment]
我修改了MainActivity中的startScanDevice()，增加了异常处理，但没有测试能不能扫描和连接CLASSIC蓝牙，我也不知道这么些是否正确，感觉是API有问题，希望您指教或尽快修复：
```kotlin
 private fun startScanDevice(){
        try {
            bluetoothClient.startScan(30000, onEndScan = {
                scanning.value = false
            }) { device ->
                if(!scanDeviceList.contains(device)){
                    scanDeviceList.add(device)
                }
            }
        } catch (e: Exception) {
            Timber.e(e, "Failed to start Bluetooth scan due to an exception.")
            showToast("$e")
        }
    }
```

**Comment by zhzc0x** [comment]
麻烦提供下你的测试机型和Android系统版本，我这边暂时没有复现出来

**Comment by Dachui-Xu** [comment]
机型：三星note20ultra
Android版本：13

**Comment by zhzc0x** [comment]
我手里没有这个机型，帮忙测试下这个版本，感谢！如果没问题我再发布release
implementation("com.zhzc0x.bluetooth:client-android:1.0.4-SNAPSHOT")

> 机型：三星note20ultra Android版本：13

**Comment by Dachui-Xu** [comment]
> 我手里没有这个机型，帮忙测试下这个版本，感谢！如果没问题我再发布release implementation("com.zhzc0x.bluetooth:client-android:1.0.4-SNAPSHOT")
> 
> > 机型：三星note20ultra Android版本：13

没有这个版本，只有1.0.3，我试了1.0.3也是一样的。
![image](https://github.com/zhzc0x/BluetoothAssistant/assets/82662185/5da5c354-cbbe-4746-9560-21df10c6be87)

**Comment by zhzc0x** [comment]
> > 我手里没有这个机型，帮忙测试下这个版本，感谢！如果没问题我再发布release implementation("com.zhzc0x.bluetooth:client-android:1.0.4-SNAPSHOT")
> > > 机型：三星note20ultra Android版本：13
> 
> 没有这个版本，只有1.0.3，我试了1.0.3也是一样的。 ![image](https://private-user-images.githubusercontent.com/82662185/341631574-5da5c354-cbbe-4746-9560-21df10c6be87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5Njk5NzMsIm5iZiI6MTcxODk2OTY3MywicGF0aCI6Ii84MjY2MjE4NS8zNDE2MzE1NzQtNWRhNWMzNTQtY2JiZS00NzQ2LTk1NjAtMjFkZjEwYzZiZTg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDExMzQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4MmU2MDNhZTRkY2NkNjc5NzA3MmExYjNiYWY0NDc0NzE0NzcwYWIxYjlkMmFiYzVkYzc2MzM1OWI3ZTEyMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X1tj-Ar1xBOGiFzUG01nv6GvSbfW3NOpR5LotN1cfzA)

 maven要加上这个地址，项目里有的，或者拉一下最新的项目代码
maven(url="https://s01.oss.sonatype.org/content/repositories/snapshots/")

**Comment by zhzc0x** [comment]
Release1.0.4已发布

**Comment by Dachui-Xu** [comment]
> > > 我手里没有这个机型，帮忙测试下这个版本，感谢！如果没问题我再发布release implementation("com.zhzc0x.bluetooth:client-android:1.0.4-SNAPSHOT")
> > > > 机型：三星note20ultra Android版本：13
> > 
> > 
> > 没有这个版本，只有1.0.3，我试了1.0.3也是一样的。 ![image](https://private-user-images.githubusercontent.com/82662185/341631574-5da5c354-cbbe-4746-9560-21df10c6be87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5Njk5NzMsIm5iZiI6MTcxODk2OTY3MywicGF0aCI6Ii84MjY2MjE4NS8zNDE2MzE1NzQtNWRhNWMzNTQtY2JiZS00NzQ2LTk1NjAtMjFkZjEwYzZiZTg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDExMzQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4MmU2MDNhZTRkY2NkNjc5NzA3MmExYjNiYWY0NDc0NzE0NzcwYWIxYjlkMmFiYzVkYzc2MzM1OWI3ZTEyMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X1tj-Ar1xBOGiFzUG01nv6GvSbfW3NOpR5LotN1cfzA)
> 
> maven要加上这个地址，项目里有的，或者拉一下最新的项目代码 maven(url="https://s01.oss.sonatype.org/content/repositories/snapshots/")

这几天忘记测试了，确实没错误了。

**Comment by zhzc0x** [comment]
麻烦给点个star哈

**Comment by Dachui-Xu** [comment]
> 麻烦给点个star哈

哈哈，给了👍
